---
# defaults file for roles/zabbix_agent
#
# ---
zabbix_agent_server_ip: "192.168.1.53"
zabbix_agent_server: "{{ zabbix_agent_server_ip }}"
zabbix_agent_server_active: "{{ zabbix_agent_server_ip }}"
