---
ad_join_domain: "ad.homelab.local"
ad_join_realm: "AD.HOMELAB.LOCAL"
ad_join_dns_server: "192.168.1.110"
ad_join_admin_group: "linux-admins@ad.homelab.local"

ad_join_packages:
  - realmd
  - sssd
  - sssd-tools
  - adcli
  - krb5-workstation
  - oddjob
  - oddjob-mkhomedir
  - samba-common-tools

ad_join_computer_ou: "OU=Linux Servers,DC=ad,DC=homelab,DC=local"
