[webservers]
web01 ansible_host=192.168.1.101
web02 ansible_host=192.168.1.102

[appservers]
app01 ansible_host=192.168.1.103

[dbservers]
db01 ansible_host=192.168.1.104

[linux_servers:children]
webservers
appservers
dbservers
loadbalancers
[linux_servers:vars]
ansible_user=ansible
ansible_become=true
ansible_python_interpreter=/usr/bin/python3
[loadbalancers]
lb01 ansible_host=192.168.1.105
