---
- name: Pre-Hardening Security Audit
  hosts: linux_servers
  become: true
  gather_facts: true

  tasks:

    - name: Check SELinux status
      ansible.builtin.command: getenforce
      register: selinux_status
      changed_when: false

    - name: Check SSH effective configuration
      ansible.builtin.shell: |
        set -o pipefail
        sshd -T | grep -E '^(permitrootlogin|passwordauthentication|pubkeyauthentication|maxauthtries) '
      args:
        executable: /bin/bash
      register: ssh_status
      changed_when: false

    - name: Check firewalld state
      ansible.builtin.command: firewall-cmd --state
      register: firewall_status
      changed_when: false

    - name: Check currently allowed firewall services
      ansible.builtin.command: firewall-cmd --list-all
      register: firewall_rules
      changed_when: false


    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Check auditd status
      ansible.builtin.set_fact:
        auditd_status_value: "{{ ansible_facts.services['auditd.service'].state | default('not-found') }}"


    - name: Check failed SSH logins
      ansible.builtin.shell: |
        set -o pipefail
        journalctl -u sshd --since "24 hours ago" --no-pager |
        grep -Ei 'failed password|authentication failure' |
        tail -10 || true
      args:
        executable: /bin/bash
      register: failed_logins
      changed_when: false

    - name: Display security audit
      ansible.builtin.debug:
        msg:
          - "HOST: {{ inventory_hostname }}"
          - "SELinux: {{ selinux_status.stdout }}"
          - "Firewall: {{ firewall_status.stdout }}"
          - "Auditd: {{ auditd_status_value }}"
          - "SSH: {{ ssh_status.stdout_lines }}"
          - "Firewall Rules: {{ firewall_rules.stdout_lines }}"
          - "Recent Failed SSH: {{ failed_logins.stdout_lines }}"
